### ISSUE TITLE
Score display View

### ISSUE THREAD

**Issue by sarfarajansari** [Freelancing-Club/freelanceArenaScoreApp#3]
This view should include current score of the participant, club logo and  VIT Logo

**Comment by sarfarajansari** [comment]
@manojkp08  Please share some screenshots of the UI

**Comment by manojkp08** [comment]
Here are some screenshots of splash screen, login screen and signup activity.

![Screenshot_20240116_192435](https://github.com/Freelancing-Club/freelanceArenaScoreApp/assets/122171992/6d024e14-31e1-417f-90b9-57e7ae71a85c)
![Screenshot_20240116_192945](https://github.com/Freelancing-Club/freelanceArenaScoreApp/assets/122171992/7134abe6-f599-41a3-aa5a-6f0ae9ed611e)
![Screenshot_20240116_194027](https://github.com/Freelancing-Club/freelanceArenaScoreApp/assets/122171992/da2522ac-12a8-403a-819c-2cc8a7053e87)

**Comment by manojkp08** [comment]
Functionality for viewing score is added.
